name: My First Workflow
on:
  # This section (push, branches and - main say this worklflow will be ran if a push is sent to the branch main
  push: # <- webhook trigger
    branches: 
    - main
  # having workflow_dispatch will determine if you can manually run the workflow.  
  workflow_dispatch: 
    inputs:
      words:
        required: true
  
# jobs are what are ran in the workflow. Must have a name (MyFirstJob and what the job will run on (latest Ubuntu os in this example). 
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    
    # Steps are the actions taken in the job. Multiple steps can be in the job. The - name: portion of steps is not needed. Can imply use - run: or - uses: etc..
    steps:
      - run: echo "${{ inputs.words }} live from ${{ github.repository }}"

      # Checking out a repo allows access to the content within the repo. Example: For the step "List files of repo" If this is not set, it will return 0 files.
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files of repo
        run: |
          echo "The repo ${{ github.repository }} contains the following files:"
            tree


      
      
  
