name: My First Workflow
on:
  # This section (push, branches and - main say this worklflow will be ran if a push is sent to the branch main
  push: 
    branches: 
    - main
  # having workflow_dispatch will determine if you can manually run the workflow.  
  workflow_dispatch: # <- determins if you can manually run the workflow.

#jobs:
  #MyFirstJob:
    #runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"

      - name: Checkout-Git-Repo
        uses: actions/checkout@v4.2.2

      - name: List files of repo
        run: |
          echo "The repo ${{ github.repositor }} contains the following files:"
          tree


      
      
  
